.class public interface abstract Lin/dragonbra/javasteam/protobufs/steamclient/SteammessagesClientserverFriends$CMsgClientChangeStatusOrBuilder;
.super Ljava/lang/Object;
.source "SteammessagesClientserverFriends.java"

# interfaces
.implements Lcom/google/protobuf/MessageOrBuilder;


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lin/dragonbra/javasteam/protobufs/steamclient/SteammessagesClientserverFriends;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x609
    name = "CMsgClientChangeStatusOrBuilder"
.end annotation


# virtual methods
.method public abstract getHighPriority()Z
.end method

.method public abstract getIsAutoGeneratedName()Z
.end method

.method public abstract getIsClientIdle()Z
.end method

.method public abstract getNeedPersonaResponse()Z
.end method

.method public abstract getPersonaSetByUser()Z
.end method

.method public abstract getPersonaState()I
.end method

.method public abstract getPersonaStateFlags()I
.end method

.method public abstract getPlayerName()Ljava/lang/String;
.end method

.method public abstract getPlayerNameBytes()Lcom/google/protobuf/ByteString;
.end method

.method public abstract hasHighPriority()Z
.end method

.method public abstract hasIsAutoGeneratedName()Z
.end method

.method public abstract hasIsClientIdle()Z
.end method

.method public abstract hasNeedPersonaResponse()Z
.end method

.method public abstract hasPersonaSetByUser()Z
.end method

.method public abstract hasPersonaState()Z
.end method

.method public abstract hasPersonaStateFlags()Z
.end method

.method public abstract hasPlayerName()Z
.end method
