.class public Lcom/px/ProxyActivity;
.super Landroid/app/Activity;


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/px/ProxyActivity$SingleInstanceP19;,
        Lcom/px/ProxyActivity$StandardP19_3;,
        Lcom/px/ProxyActivity$StandardP19_2;,
        Lcom/px/ProxyActivity$StandardP19_1;,
        Lcom/px/ProxyActivity$StandardP19_0;,
        Lcom/px/ProxyActivity$SingleTopP19_3;,
        Lcom/px/ProxyActivity$SingleTopP19_2;,
        Lcom/px/ProxyActivity$SingleTopP19_1;,
        Lcom/px/ProxyActivity$SingleTopP19_0;,
        Lcom/px/ProxyActivity$SingleTaskP19_3;,
        Lcom/px/ProxyActivity$SingleTaskP19_2;,
        Lcom/px/ProxyActivity$SingleTaskP19_1;,
        Lcom/px/ProxyActivity$SingleTaskP19_0;,
        Lcom/px/ProxyActivity$SingleInstanceP18;,
        Lcom/px/ProxyActivity$StandardP18_3;,
        Lcom/px/ProxyActivity$StandardP18_2;,
        Lcom/px/ProxyActivity$StandardP18_1;,
        Lcom/px/ProxyActivity$StandardP18_0;,
        Lcom/px/ProxyActivity$SingleTopP18_3;,
        Lcom/px/ProxyActivity$SingleTopP18_2;,
        Lcom/px/ProxyActivity$SingleTopP18_1;,
        Lcom/px/ProxyActivity$SingleTopP18_0;,
        Lcom/px/ProxyActivity$SingleTaskP18_3;,
        Lcom/px/ProxyActivity$SingleTaskP18_2;,
        Lcom/px/ProxyActivity$SingleTaskP18_1;,
        Lcom/px/ProxyActivity$SingleTaskP18_0;,
        Lcom/px/ProxyActivity$SingleInstanceP17;,
        Lcom/px/ProxyActivity$StandardP17_3;,
        Lcom/px/ProxyActivity$StandardP17_2;,
        Lcom/px/ProxyActivity$StandardP17_1;,
        Lcom/px/ProxyActivity$StandardP17_0;,
        Lcom/px/ProxyActivity$SingleTopP17_3;,
        Lcom/px/ProxyActivity$SingleTopP17_2;,
        Lcom/px/ProxyActivity$SingleTopP17_1;,
        Lcom/px/ProxyActivity$SingleTopP17_0;,
        Lcom/px/ProxyActivity$SingleTaskP17_3;,
        Lcom/px/ProxyActivity$SingleTaskP17_2;,
        Lcom/px/ProxyActivity$SingleTaskP17_1;,
        Lcom/px/ProxyActivity$SingleTaskP17_0;,
        Lcom/px/ProxyActivity$SingleInstanceP16;,
        Lcom/px/ProxyActivity$StandardP16_3;,
        Lcom/px/ProxyActivity$StandardP16_2;,
        Lcom/px/ProxyActivity$StandardP16_1;,
        Lcom/px/ProxyActivity$StandardP16_0;,
        Lcom/px/ProxyActivity$SingleTopP16_3;,
        Lcom/px/ProxyActivity$SingleTopP16_2;,
        Lcom/px/ProxyActivity$SingleTopP16_1;,
        Lcom/px/ProxyActivity$SingleTopP16_0;,
        Lcom/px/ProxyActivity$SingleTaskP16_3;,
        Lcom/px/ProxyActivity$SingleTaskP16_2;,
        Lcom/px/ProxyActivity$SingleTaskP16_1;,
        Lcom/px/ProxyActivity$SingleTaskP16_0;,
        Lcom/px/ProxyActivity$SingleInstanceP15;,
        Lcom/px/ProxyActivity$StandardP15_3;,
        Lcom/px/ProxyActivity$StandardP15_2;,
        Lcom/px/ProxyActivity$StandardP15_1;,
        Lcom/px/ProxyActivity$StandardP15_0;,
        Lcom/px/ProxyActivity$SingleTopP15_3;,
        Lcom/px/ProxyActivity$SingleTopP15_2;,
        Lcom/px/ProxyActivity$SingleTopP15_1;,
        Lcom/px/ProxyActivity$SingleTopP15_0;,
        Lcom/px/ProxyActivity$SingleTaskP15_3;,
        Lcom/px/ProxyActivity$SingleTaskP15_2;,
        Lcom/px/ProxyActivity$SingleTaskP15_1;,
        Lcom/px/ProxyActivity$SingleTaskP15_0;,
        Lcom/px/ProxyActivity$SingleInstanceP14;,
        Lcom/px/ProxyActivity$StandardP14_3;,
        Lcom/px/ProxyActivity$StandardP14_2;,
        Lcom/px/ProxyActivity$StandardP14_1;,
        Lcom/px/ProxyActivity$StandardP14_0;,
        Lcom/px/ProxyActivity$SingleTopP14_3;,
        Lcom/px/ProxyActivity$SingleTopP14_2;,
        Lcom/px/ProxyActivity$SingleTopP14_1;,
        Lcom/px/ProxyActivity$SingleTopP14_0;,
        Lcom/px/ProxyActivity$SingleTaskP14_3;,
        Lcom/px/ProxyActivity$SingleTaskP14_2;,
        Lcom/px/ProxyActivity$SingleTaskP14_1;,
        Lcom/px/ProxyActivity$SingleTaskP14_0;,
        Lcom/px/ProxyActivity$SingleInstanceP13;,
        Lcom/px/ProxyActivity$StandardP13_3;,
        Lcom/px/ProxyActivity$StandardP13_2;,
        Lcom/px/ProxyActivity$StandardP13_1;,
        Lcom/px/ProxyActivity$StandardP13_0;,
        Lcom/px/ProxyActivity$SingleTopP13_3;,
        Lcom/px/ProxyActivity$SingleTopP13_2;,
        Lcom/px/ProxyActivity$SingleTopP13_1;,
        Lcom/px/ProxyActivity$SingleTopP13_0;,
        Lcom/px/ProxyActivity$SingleTaskP13_3;,
        Lcom/px/ProxyActivity$SingleTaskP13_2;,
        Lcom/px/ProxyActivity$SingleTaskP13_1;,
        Lcom/px/ProxyActivity$SingleTaskP13_0;,
        Lcom/px/ProxyActivity$SingleInstanceP12;,
        Lcom/px/ProxyActivity$StandardP12_3;,
        Lcom/px/ProxyActivity$StandardP12_2;,
        Lcom/px/ProxyActivity$StandardP12_1;,
        Lcom/px/ProxyActivity$StandardP12_0;,
        Lcom/px/ProxyActivity$SingleTopP12_3;,
        Lcom/px/ProxyActivity$SingleTopP12_2;,
        Lcom/px/ProxyActivity$SingleTopP12_1;,
        Lcom/px/ProxyActivity$SingleTopP12_0;,
        Lcom/px/ProxyActivity$SingleTaskP12_3;,
        Lcom/px/ProxyActivity$SingleTaskP12_2;,
        Lcom/px/ProxyActivity$SingleTaskP12_1;,
        Lcom/px/ProxyActivity$SingleTaskP12_0;,
        Lcom/px/ProxyActivity$SingleInstanceP11;,
        Lcom/px/ProxyActivity$StandardP11_3;,
        Lcom/px/ProxyActivity$StandardP11_2;,
        Lcom/px/ProxyActivity$StandardP11_1;,
        Lcom/px/ProxyActivity$StandardP11_0;,
        Lcom/px/ProxyActivity$SingleTopP11_3;,
        Lcom/px/ProxyActivity$SingleTopP11_2;,
        Lcom/px/ProxyActivity$SingleTopP11_1;,
        Lcom/px/ProxyActivity$SingleTopP11_0;,
        Lcom/px/ProxyActivity$SingleTaskP11_3;,
        Lcom/px/ProxyActivity$SingleTaskP11_2;,
        Lcom/px/ProxyActivity$SingleTaskP11_1;,
        Lcom/px/ProxyActivity$SingleTaskP11_0;,
        Lcom/px/ProxyActivity$SingleInstanceP10;,
        Lcom/px/ProxyActivity$StandardP10_3;,
        Lcom/px/ProxyActivity$StandardP10_2;,
        Lcom/px/ProxyActivity$StandardP10_1;,
        Lcom/px/ProxyActivity$StandardP10_0;,
        Lcom/px/ProxyActivity$SingleTopP10_3;,
        Lcom/px/ProxyActivity$SingleTopP10_2;,
        Lcom/px/ProxyActivity$SingleTopP10_1;,
        Lcom/px/ProxyActivity$SingleTopP10_0;,
        Lcom/px/ProxyActivity$SingleTaskP10_3;,
        Lcom/px/ProxyActivity$SingleTaskP10_2;,
        Lcom/px/ProxyActivity$SingleTaskP10_1;,
        Lcom/px/ProxyActivity$SingleTaskP10_0;,
        Lcom/px/ProxyActivity$SingleInstanceP9;,
        Lcom/px/ProxyActivity$StandardP9_3;,
        Lcom/px/ProxyActivity$StandardP9_2;,
        Lcom/px/ProxyActivity$StandardP9_1;,
        Lcom/px/ProxyActivity$StandardP9_0;,
        Lcom/px/ProxyActivity$SingleTopP9_3;,
        Lcom/px/ProxyActivity$SingleTopP9_2;,
        Lcom/px/ProxyActivity$SingleTopP9_1;,
        Lcom/px/ProxyActivity$SingleTopP9_0;,
        Lcom/px/ProxyActivity$SingleTaskP9_3;,
        Lcom/px/ProxyActivity$SingleTaskP9_2;,
        Lcom/px/ProxyActivity$SingleTaskP9_1;,
        Lcom/px/ProxyActivity$SingleTaskP9_0;,
        Lcom/px/ProxyActivity$SingleInstanceP8;,
        Lcom/px/ProxyActivity$StandardP8_3;,
        Lcom/px/ProxyActivity$StandardP8_2;,
        Lcom/px/ProxyActivity$StandardP8_1;,
        Lcom/px/ProxyActivity$StandardP8_0;,
        Lcom/px/ProxyActivity$SingleTopP8_3;,
        Lcom/px/ProxyActivity$SingleTopP8_2;,
        Lcom/px/ProxyActivity$SingleTopP8_1;,
        Lcom/px/ProxyActivity$SingleTopP8_0;,
        Lcom/px/ProxyActivity$SingleTaskP8_3;,
        Lcom/px/ProxyActivity$SingleTaskP8_2;,
        Lcom/px/ProxyActivity$SingleTaskP8_1;,
        Lcom/px/ProxyActivity$SingleTaskP8_0;,
        Lcom/px/ProxyActivity$SingleInstanceP7;,
        Lcom/px/ProxyActivity$StandardP7_3;,
        Lcom/px/ProxyActivity$StandardP7_2;,
        Lcom/px/ProxyActivity$StandardP7_1;,
        Lcom/px/ProxyActivity$StandardP7_0;,
        Lcom/px/ProxyActivity$SingleTopP7_3;,
        Lcom/px/ProxyActivity$SingleTopP7_2;,
        Lcom/px/ProxyActivity$SingleTopP7_1;,
        Lcom/px/ProxyActivity$SingleTopP7_0;,
        Lcom/px/ProxyActivity$SingleTaskP7_3;,
        Lcom/px/ProxyActivity$SingleTaskP7_2;,
        Lcom/px/ProxyActivity$SingleTaskP7_1;,
        Lcom/px/ProxyActivity$SingleTaskP7_0;,
        Lcom/px/ProxyActivity$SingleInstanceP6;,
        Lcom/px/ProxyActivity$StandardP6_3;,
        Lcom/px/ProxyActivity$StandardP6_2;,
        Lcom/px/ProxyActivity$StandardP6_1;,
        Lcom/px/ProxyActivity$StandardP6_0;,
        Lcom/px/ProxyActivity$SingleTopP6_3;,
        Lcom/px/ProxyActivity$SingleTopP6_2;,
        Lcom/px/ProxyActivity$SingleTopP6_1;,
        Lcom/px/ProxyActivity$SingleTopP6_0;,
        Lcom/px/ProxyActivity$SingleTaskP6_3;,
        Lcom/px/ProxyActivity$SingleTaskP6_2;,
        Lcom/px/ProxyActivity$SingleTaskP6_1;,
        Lcom/px/ProxyActivity$SingleTaskP6_0;,
        Lcom/px/ProxyActivity$SingleInstanceP5;,
        Lcom/px/ProxyActivity$StandardP5_3;,
        Lcom/px/ProxyActivity$StandardP5_2;,
        Lcom/px/ProxyActivity$StandardP5_1;,
        Lcom/px/ProxyActivity$StandardP5_0;,
        Lcom/px/ProxyActivity$SingleTopP5_3;,
        Lcom/px/ProxyActivity$SingleTopP5_2;,
        Lcom/px/ProxyActivity$SingleTopP5_1;,
        Lcom/px/ProxyActivity$SingleTopP5_0;,
        Lcom/px/ProxyActivity$SingleTaskP5_3;,
        Lcom/px/ProxyActivity$SingleTaskP5_2;,
        Lcom/px/ProxyActivity$SingleTaskP5_1;,
        Lcom/px/ProxyActivity$SingleTaskP5_0;,
        Lcom/px/ProxyActivity$SingleInstanceP4;,
        Lcom/px/ProxyActivity$StandardP4_3;,
        Lcom/px/ProxyActivity$StandardP4_2;,
        Lcom/px/ProxyActivity$StandardP4_1;,
        Lcom/px/ProxyActivity$StandardP4_0;,
        Lcom/px/ProxyActivity$SingleTopP4_3;,
        Lcom/px/ProxyActivity$SingleTopP4_2;,
        Lcom/px/ProxyActivity$SingleTopP4_1;,
        Lcom/px/ProxyActivity$SingleTopP4_0;,
        Lcom/px/ProxyActivity$SingleTaskP4_3;,
        Lcom/px/ProxyActivity$SingleTaskP4_2;,
        Lcom/px/ProxyActivity$SingleTaskP4_1;,
        Lcom/px/ProxyActivity$SingleTaskP4_0;,
        Lcom/px/ProxyActivity$SingleInstanceP3;,
        Lcom/px/ProxyActivity$StandardP3_3;,
        Lcom/px/ProxyActivity$StandardP3_2;,
        Lcom/px/ProxyActivity$StandardP3_1;,
        Lcom/px/ProxyActivity$StandardP3_0;,
        Lcom/px/ProxyActivity$SingleTopP3_3;,
        Lcom/px/ProxyActivity$SingleTopP3_2;,
        Lcom/px/ProxyActivity$SingleTopP3_1;,
        Lcom/px/ProxyActivity$SingleTopP3_0;,
        Lcom/px/ProxyActivity$SingleTaskP3_3;,
        Lcom/px/ProxyActivity$SingleTaskP3_2;,
        Lcom/px/ProxyActivity$SingleTaskP3_1;,
        Lcom/px/ProxyActivity$SingleTaskP3_0;,
        Lcom/px/ProxyActivity$SingleInstanceP2;,
        Lcom/px/ProxyActivity$StandardP2_3;,
        Lcom/px/ProxyActivity$StandardP2_2;,
        Lcom/px/ProxyActivity$StandardP2_1;,
        Lcom/px/ProxyActivity$StandardP2_0;,
        Lcom/px/ProxyActivity$SingleTopP2_3;,
        Lcom/px/ProxyActivity$SingleTopP2_2;,
        Lcom/px/ProxyActivity$SingleTopP2_1;,
        Lcom/px/ProxyActivity$SingleTopP2_0;,
        Lcom/px/ProxyActivity$SingleTaskP2_3;,
        Lcom/px/ProxyActivity$SingleTaskP2_2;,
        Lcom/px/ProxyActivity$SingleTaskP2_1;,
        Lcom/px/ProxyActivity$SingleTaskP2_0;,
        Lcom/px/ProxyActivity$SingleInstanceP1;,
        Lcom/px/ProxyActivity$StandardP1_3;,
        Lcom/px/ProxyActivity$StandardP1_2;,
        Lcom/px/ProxyActivity$StandardP1_1;,
        Lcom/px/ProxyActivity$StandardP1_0;,
        Lcom/px/ProxyActivity$SingleTopP1_3;,
        Lcom/px/ProxyActivity$SingleTopP1_2;,
        Lcom/px/ProxyActivity$SingleTopP1_1;,
        Lcom/px/ProxyActivity$SingleTopP1_0;,
        Lcom/px/ProxyActivity$SingleTaskP1_3;,
        Lcom/px/ProxyActivity$SingleTaskP1_2;,
        Lcom/px/ProxyActivity$SingleTaskP1_1;,
        Lcom/px/ProxyActivity$SingleTaskP1_0;,
        Lcom/px/ProxyActivity$SingleInstanceP0;,
        Lcom/px/ProxyActivity$StandardP0_3;,
        Lcom/px/ProxyActivity$StandardP0_2;,
        Lcom/px/ProxyActivity$StandardP0_1;,
        Lcom/px/ProxyActivity$StandardP0_0;,
        Lcom/px/ProxyActivity$SingleTopP0_3;,
        Lcom/px/ProxyActivity$SingleTopP0_2;,
        Lcom/px/ProxyActivity$SingleTopP0_1;,
        Lcom/px/ProxyActivity$SingleTopP0_0;,
        Lcom/px/ProxyActivity$SingleTaskP0_3;,
        Lcom/px/ProxyActivity$SingleTaskP0_2;,
        Lcom/px/ProxyActivity$SingleTaskP0_1;,
        Lcom/px/ProxyActivity$SingleTaskP0_0;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Landroid/app/Activity;-><init>()V

    return-void
.end method


# virtual methods
.method public onCreate(Landroid/os/Bundle;)V
    .locals 0

    .line 1
    invoke-super {p0, p1}, Landroid/app/Activity;->onCreate(Landroid/os/Bundle;)V

    .line 2
    .line 3
    .line 4
    invoke-virtual {p0}, Landroid/app/Activity;->finish()V

    .line 5
    .line 6
    .line 7
    invoke-virtual {p0}, Landroid/app/Activity;->getIntent()Landroid/content/Intent;

    .line 8
    .line 9
    .line 10
    move-result-object p1

    .line 11
    invoke-static {p1, p0}, Lcd/al;->b(Landroid/content/Intent;Landroid/app/Activity;)V

    .line 12
    .line 13
    .line 14
    return-void
.end method
